[package]
name = "test-to-vec"
version = "0.4.1"
authors = ["Joe Grund <joe.grund@intel.com>"]
keywords = ["test", "cargo"]
license = "MIT"
repository = "https://github.com/rustation/test-to-vec"
description = "Converts cargo test output into a vec of suites"

[dependencies]
nom = "2.0.1"
